### ISSUE TITLE
ftn-unpack AttributeError: 'module' object has no attribute 'errors'

### ISSUE THREAD

**Issue by ftoledo** [larsks/python-ftn#4]
i don't know  if this a pkt file malformed or from ftn-unpack code.
the message was created in Synchronet bbs as netmail. 
The path is:
synchronet -> sbbsecho -> binkd (bbs side) -> binkd (client side) -> ftn-unpack
BBS side run debian wheezy,  client side (mi laptop) run debian jessie.

ragnarok@jola:/tmp$ ftn-unpack b3ed89bc.pkt -d rr/ --debug
2014-08-02 23:21:58 app:DEBUG [5556] set umask to 0022.
2014-08-02 23:21:58 app:DEBUG [5556] reading config from ./fidonet.cfg
2014-08-02 23:21:58 app:DEBUG [5556] finished generic setup
2014-08-02 23:21:58 messagefactory:DEBUG [5556] msgVersion == 2; assuming this is an FTS-0001 (C) message.
2014-08-02 23:21:58 bitparser:DEBUG [5556] packing field msgVersion as "uintle:16"
2014-08-02 23:21:58 bitparser:DEBUG [5556] packing field origNode as "uintle:16"
2014-08-02 23:21:58 bitparser:DEBUG [5556] packing field destNode as "uintle:16"
2014-08-02 23:21:58 bitparser:DEBUG [5556] packing field origNet as "uintle:16"
2014-08-02 23:21:58 bitparser:DEBUG [5556] packing field destNet as "uintle:16"
2014-08-02 23:21:58 bitparser:DEBUG [5556] packing field attributeWord as "bits:16"
2014-08-02 23:21:58 bitparser:DEBUG [5556] packing field cost as "uintle:16"
2014-08-02 23:21:58 bitparser:DEBUG [5556] packing field dateTime as "bytes:20"
2014-08-02 23:21:58 bitparser:DEBUG [5556] packing field toUsername as "bytes, 0x00"
2014-08-02 23:21:58 bitparser:DEBUG [5556] packing field fromUsername as "bytes, 0x00"
2014-08-02 23:21:58 bitparser:DEBUG [5556] packing field subject as "bytes, 0x00"
2014-08-02 23:21:58 bitparser:DEBUG [5556] packing field body as "bytes, 0x00"
2014-08-02 23:21:58 unpack:DEBUG [5556] wrote message from b3ed89bc.pkt to rr/4.msg
Traceback (most recent call last):
  File "/usr/local/bin/ftn-unpack", line 9, in <module>
    load_entry_point('python-ftn==1.0.0', 'console_scripts', 'ftn-unpack')()
  File "/usr/local/lib/python2.7/dist-packages/fidonet/app.py", line 14, in run
    return app.main()
  File "/usr/local/lib/python2.7/dist-packages/fidonet/app.py", line 40, in main
    self.handle_args(args)
  File "/usr/local/lib/python2.7/dist-packages/fidonet/apps/unpack.py", line 39, in handle_args
    msg = fidonet.MessageFactory(pkt.messages)
  File "/usr/local/lib/python2.7/dist-packages/fidonet/messagefactory.py", line 18, in MessageFactory
    msg = packedmessage.MessageParser.parse(bits)
  File "/usr/local/lib/python2.7/dist-packages/fidonet/bitparser.py", line 101, in parse
    except bitstring.errors.ReadError:
AttributeError: 'module' object has no attribute 'errors'
ragnarok@jola:/tmp$ 

you can download the .pkt file at http://bbs.docksud.com.ar/download/b3ed89bc.pkt

pd: great project, i hope to colabore with this.

**Comment by streaps** [comment]
newer bitstring versions use `bitstring.ReadError` instead of `bitstring.errors.ReadError`

**Comment by larsks** [comment]
Hi, thanks for looking at this code!  I haven't touched it in quite a while, and I'm no longer running any FTN-compatible software. If you want to submit a pull request that corrects the issue I'm happy to accept it.
